version: "2"
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "8080:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"

    # logging:
    #   driver: none

  # sender:
  #   build: ./sender
  #   links:
  #     - rabbitmq

  #   depends_on:
  #     - rabbitmq

  # consumer:
  #   build: ./consumer
  #   links:
  #     - rabbitmq
  #   depends_on:
  #     - rabbitmq